src/bookings/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.filter_bookings, name = 'bookings'),
    path('create/', views.create_booking, name = 'createbooking'),
    path('feedback/', views.feedback_view, name='feedback'),
    path('<int:booking_id>/join', views.join_booking, name='join'),
    path('<int:booking_id>/leave', views.leave_booking, name='leave'),
    path('<int:booking_id>/info', views.booking_info, name='booking_info'),
    path('<int:booking_id>/update', views.update_booking, name='update'),
    path('<int:booking_id>/delete', views.delete_booking, name='delete'),
    path('filter/', views.filter_bookings, name = 'filter'),
]

src/chat/urls.py
from django.urls import path, re_path
from .views import index, room


app_name = 'chat'

urlpatterns = [
    path('', index, name='index'),
    re_path(r'^(?P<room_name>[^/]+)/$', room, name='room'),
]

src/justchat/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib import admin
from django.urls import path, include
from bookings import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.main, name='home'),
    path('chat/', include('chat.urls', namespace='chat')),
    path('accounts/', include('accounts.urls')),
    path('bookings/', include('bookings.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

src/bookings/models.py
from django.db import models
from django.contrib.auth.models import User





GENDER=(
    ('all','all'),
    ('girls only','girls only'),
    ('boys only', 'boys only')
)



class createbooking(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,default=1)
    time = models.TimeField(help_text="format (hh:mm:ss)")
    date = models.DateField(help_text="format (yyyy-mm-dd)")
    pickup = models.CharField(max_length=255)
    destination = models.CharField(max_length=255)
    luggage = models.DecimalField(help_text="Please enter the value in kg maximum upto two decimal places", decimal_places=2, max_digits=5)
    peopletogether = models.IntegerField(default=1)
    budget = models.CharField(max_length=50)
    is_drop = models.BooleanField(default=False)
    gender_choice=models.CharField(default='both', max_length=15, choices=GENDER)

    def __str__(self):
        return "from " + self.pickup+ " to " + self.destination + " at " + str(self.date) + " " + str(self.time) + "-/-" +str(self.pk)




class Feedback(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE , blank=True)
    details = models.TextField()

    def __str__(self):
        return self.user.username


class Member(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    booking = models.ForeignKey('createbooking', on_delete=models.CASCADE, related_name='members')

src/bookings/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Feedback
from .models import createbooking, Member
import datetime

GENDER=(
    ('all','all'),
    ('girls only','girls only'),
    ('boys only', 'boys only')
)


class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        fields = ['details']


class BookingForm(forms.ModelForm):
    time = forms.TimeField(widget=forms.TimeInput, label="Time (Enter in format hh:mm:ss)")
    date = forms.DateField(widget=forms.DateInput ,initial=datetime.date.today)
    pickup = forms.CharField(label = "Pick Up Location")
    destination = forms.CharField(label = "Drop Location")
    peopletogether = forms.IntegerField(label = "People Together")
    luggage = forms.DecimalField(widget = forms.NumberInput, label = "Amount of luggage (in kg)",)
    budget = forms.CharField(label = "Your budget")
    gender_choice =forms.ChoiceField(choices=GENDER, required=True)

    class Meta:
        model = createbooking
        fields = ['time', 'date', 'pickup', 'destination' ,'peopletogether', 'luggage', 'budget', 'gender_choice']


class MemberForm(forms.ModelForm):
    class Meta():
        model=Member
        fields=[]

src/bookings/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import FeedbackForm, BookingForm, MemberForm
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from .models import createbooking, Member
from django.contrib import messages
import datetime
from .filters import BookingFilter
from accounts.models import Booker


# Create your views here.
def main(request):
    return render(request, 'bookings/home.html')

def home(request):
    books = createbooking.objects
    return render(request, 'bookings/index.html', {'books': books})


@login_required
def feedback_view(request):
    if request.method == "POST":
        form = FeedbackForm(request.POST)

        if form.is_valid():
            feedback=form.save(commit=False)
            feedback.user=request.user
            feedback.save()
            return render(request, 'bookings/feedback_submitted.html')

    else:
        form = FeedbackForm()
        return render(request, 'bookings/feedback.html', {'form': form})


@login_required
def create_booking(request):
    if request.method=='POST':
        booking_form = BookingForm(request.POST)

        if booking_form.is_valid():
            booking = booking_form.save(commit=False)

            if(booking.pickup == booking.destination):
                messages.error(request,  "The pickup location and destination should be different!")
                return redirect('bookings')
            booking.user = request.user
            booking.save()
            return redirect('bookings')
        else:
            return render(request,'bookings/createbooking.html',{'booking_form':booking_form})
    else:
        booking_form = BookingForm()
        return render(request,'bookings/createbooking.html',{'booking_form':booking_form})

@login_required
def join_booking(request, booking_id):
    booking = get_object_or_404(createbooking, pk=booking_id)
    if request.method == 'POST':
        form=MemberForm(request.POST)
        if form.is_valid():
            people=booking.members.all()
            for any in people:
                if(request.user.username == any.user.username):
                    messages.error(request, "You are already a member of this booking!")
                    return redirect('bookings')
            if (request.user.username == booking.user.username):
                messages.error(request, "You are the creator of this booking!")
                return redirect('bookings')
            if(booking.peopletogether < 4):
                booking.peopletogether += 1
                booking.save()
            if(booking.gender_choice=='boys only'):
                if(request.user.booker.gender == 'female'):
                    messages.error(request,  "Girls can't join BOYS ONLY bookings!")
                    return redirect('bookings')

            if(booking.gender_choice=='girls only'):
                if(request.user.booker.gender == 'male'):
                    messages.error(request,  "Boys can't join  GIRLS ONLY bookings!")
                    return redirect('bookings')

            member=form.save(commit=False)
            member.booking= booking
            member.user = request.user
            member.save()
            return render(request, "bookings/home.html", {'succ': 'Booking joined successfully!'})
    else:
        form = MemberForm()
        if(booking.user.username == request.user.username):
            messages.error(request, "You are the booking creator!")
            return redirect('bookings')

        else:
            if(booking.gender_choice=='boys only'):
                if(request.user.booker.gender == 'female'):
                    messages.success(request,  "Girls can't join BOYS ONLY bookings!")
                    return redirect('bookings')

            if(booking.gender_choice=='girls only'):
                if(request.user.booker.gender == 'male'):
                    messages.error(request,  "Boys can't join GIRLS ONLY bookings!")
                    return redirect('bookings')
            return render(request, 'bookings/member_join.html', {'form':form})


@login_required
def leave_booking(request, booking_id):
    booking=get_object_or_404(createbooking, pk=booking_id)
    if request.method=='POST':
        leaveform=MemberForm(request.POST)
        if leaveform.is_valid():
            try:
                member=booking.members.get(user=request.user)
                member.delete()
                if(booking.peopletogether > 0):
                    booking.peopletogether -= 1
                    booking.save()
                return render(request, "bookings/home.html", {'succ': 'Booking left!'})
            except Member.DoesNotExist:
                return redirect('bookings')
    else:
        leaveform=MemberForm()
        people=booking.members.all()
        for any in people:
            if(request.user.username == any.user.username):
                return render(request, 'bookings/member_leave.html', {'leaveform':leaveform})
        if(booking.user.username == request.user.username):
            messages.error(request, "You need to delete this booking!")
            return redirect('bookings')
        messages.error(request, "You are not a member of this booking!")
        return redirect('bookings')

def booking_info(request, booking_id):
    booking = get_object_or_404(createbooking, pk=booking_id)
    return render(request, 'bookings/details.html', {'booking': booking})

@login_required
def update_booking(request, booking_id):
    booking = get_object_or_404(createbooking, pk=booking_id)
    if request.method=='POST':
        booking_form=BookingForm(request.POST)
        if booking_form.is_valid():
            booking_form=booking_form.save(commit=False)
            if(booking_form.date <datetime.date.today()):
                messages.error(request, "Invalid Date!")
                return redirect('bookings')
            if (booking.user == request.user):
                booking=createbooking.objects.get(pk=booking_id)
                booking.pickup=booking_form.pickup
                booking.destination=booking_form.destination
                booking.date=booking_form.date
                booking.time=booking_form.time
                booking.budget=booking_form.budget
                booking.luggage=booking_form.luggage
                booking.peopletogether=booking_form.peopletogether
                booking.save()
                return render(request, bookings/home.html, {'succ':'Booking updated successfully!'})
            return render(request, "bookings/update.html", {'booking_form':booking_form})
    else:
        booking_form=BookingForm()
        if(booking.user == request.user):
            return render(request, "bookings/update.html", {'booking_form':booking_form})
        else:
            messages.error(request, 'You cannot update this booking!')
            return redirect('bookings')

@login_required
def delete_booking(request, booking_id):
    booking = get_object_or_404(createbooking, pk=booking_id)
    if request.method=='POST':
        if(booking.user == request.user):
            booking.delete()
            return redirect('bookings')
        else:
            messages.error(request, 'You cannot delete this booking!')
            return redirect('bookings')
    else:
        return render(request, 'bookings/delete.html')

    return redirect('bookings')


def filter_bookings(request):
    list = createbooking.objects.all()
    filter = BookingFilter(request.GET, queryset=list)
    return render(request, 'bookings/index.html', {'filter': filter})

src/bookings/templates/bookings/createbooking.html
{% extends 'base.html' %}

{% block content %}
{% load crispy_forms_tags %}
{% load static %}

{% if error %}
{{ error }}
<br />
<br />
{% endif %}

   <div class = "container book-container">

     <div class="row">
       <div class="col-md-5">
         <img src="{% static 'feedback.png' %}" width = "280" class="img-fluid">
         <br><br><br>
         <h3>Create a Booking</h3>
       </div>
       <div class="col-md-7">
         <form action="{% url 'createbooking' %}" method="POST">
           {% csrf_token %}
           {{ booking_form|crispy }}
           <input type="submit" class="btn btn-outline-success" value="Submit">
         </form>
       </div>
     </div>
  </div>

{% endblock %}

src/bookings/templates/bookings/delete.html
{% extends 'base.html' %}
  {% load static %}
{% block content %}

   <div class="container leave-container">
     <div class="row">
       <div class="col-md-4">
         <img src="{% static 'question-mark.png' %}" width = "300" class="img-fluid">
       </div>
       <div class="col-md-8">
         <form method="POST">
           {% csrf_token %}
           <h1>Are you sure you want to delete this booking?</h1>
           <br><br>
           <input type="submit" value="Delete" class='btn btn-outline-danger btn-lg'>
         </form>
       </div>
     </div>
    </div>

{% endblock %}

src/bookings/templates/bookings/details.html
{% extends 'base.html' %}
 {%  load static %}

{% block content %}

<h1 class="display-4 text-center">ABOUT MEMBERS</h1>
   <div class="container mt-5">
     <div class="row">
       <div class="col-md-3">
         <div class="card" style="width: 17rem;">
          <img src="{{booking.user.booker.dp.url}}" class="card-img-top" width="35">
           <div class="card-body">
          <h5 class="card-text"><i>Username:</i> {{booking.user.username}}</h5>
          <h5 class="card-text"><i>Email:</i> {{booking.user.email}}</h5>
          <h5 class="card-text"><i>Hostel:</i> {{booking.user.booker.hostel}}</h5>
          <p class="float-right"><i>Creator</i></p>
           </div>
          </div>
       </div>
       {% for any in booking.members.all %}
       <div class="col-md-3">
         <div class="card" style="width: 17rem;">
          <img src="{{any.user.booker.dp.url}}" class="card-img-top" width="35">
           <div class="card-body">
          <h5 class="card-text"><i>Username:</i> {{any.user.username}}</h5>
          <h5 class="card-text"><i>Email:</i> {{any.user.email}}</h5>
          <h5 class="card-text"><i>Hostel:</i> {{any.user.booker.hostel}}</h5>
           </div>
          </div>
       </div>
       {% endfor  %}
     </div>
    </div>

    <nav class="navbar navbar-expand-lg navbar-light bg-transparent">

  <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      {% if user.is_authenticated and booking.user != any.user %}
        <a class="btn btn-primary btn-sm" href="{% url 'update' booking.id  %}" role="button" style="margin:9px";>Update</a>
        <a class="btn btn-danger btn-sm" href="{% url 'delete' booking.id  %}" role="button" style="margin:9px";>Delete</a>
      {% else %}
      <a class="btn btn-primary btn-sm disabled" href="#" role="button" style="margin:9px";>Update</a>
      <a class="btn btn-danger btn-sm disabled" href="#" role="button" style="margin:9px";>Delete</a>
     {% endif %}
    </ul>

  </div>
</nav>

{% endblock %}

src/bookings/templates/bookings/feedback.html
{% extends 'base.html' %}
 {% load crispy_forms_tags %}
 {% load static %}
{% block content %}



<div class="container feedback-container">
  <div class="row feedback-row">
    <div class="col-md-5">
      <img src="{% static 'feedback.png' %}" width = "280" class="img-fluid">
      <br><br><br>
      <h4>Give Your Feedback</h4>
    </div>
    <div class="col-md-7">
      <form action="{% url 'feedback' %}" method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <input type ="submit" name="submit" value="Submit" class="btn btn-lg btn-outline-dark float-right">
      </form>
    </div>
  </div>
</div>



{% endblock %}

src/bookings/templates/bookings/feedback_submitted.html
{% extends 'base.html' %}

{% block content %}
   <h1>Thanks for your valuable feedback!</h1>
{% endblock %}

src/bookings/templates/bookings/filters.html
{% extends 'base.html' %}
 {% load crispy_forms_tags %}
 {%load static%}
 {% load widget_tweaks %}
{% block content %}

{% if error %}

  <div class="alert alert-danger" role="alert">
  {{error}}
  </div>

{% endif %}



   <div class="row">
     <div class="col-md-2">
       <img src="{% static 'taxi.png' %}"  width="80" class="img-fluid">
     </div>
     <div class="col-md-10">
       <h1 class="display-4">All Bookings</h1>
     </div>

   </div>


   <form method="GET">
    <div class="well">
      <h4 style="margin-top: 0">Filter</h4>
      <div class="row">
        <div class="form-group col-sm-4 col-md-3">
          {{ filter.form.destination.label_tag }}
          {% render_field filter.form.destination class="form-control" %}
        </div>
        <div class="form-group col-sm-4 col-md-3">
          {{ filter.form.pickup.label_tag }}
          {% render_field filter.form.pickup class="form-control" %}
        </div>
        <div class="form-group col-sm-4 col-md-3">
          {{ filter.form.date.label_tag }}
          {% render_field filter.form.date class="form-control" %}
        </div>
      </div>
      <button type="submit" class="btn btn-primary">
        <span class="glyphicon glyphicon-search"></span> Search
      </button>
    </div>
  </form>

{% for booking in filter.qs %}
 {% if booking.peopletogether == 4 %}
  <div class="card w-75 border-warning mt-4">
  <div class="card-body text-warning">
  {% else %}
  <div class="card w-75 border-success mt-4">
  <div class="card-body text-success">
    {% endif %}
    <div class="row">
      <div class="col-md-8">
       <div>
         <h3 class="card-title" style="display: inline">{{booking.pickup}} to {{booking.destination}}</h3>
          {%  for any in booking.members.all  %}
           {%  if any.user == request.user %}
              <img src="{% static 'confirm.png' %}" width = "35" class="img-fluid inline-block align-top">
            {%  endif %}
            {% endfor  %}
         </div>

        <h6>Time: {{booking.time}}</h6>
        <h6>Date: {{booking.date}}</h6>
        <h6>Members: {{booking.peopletogether}}</h6>
        <h6>Budget: {{booking.budget}}</h6>
        <h6>luggage: {{booking.luggage}}</h6>
        <h6>Created By: {{booking.user}}</h6>
      </div>
      <div class="col-md-4">


            {% if booking.peopletogether == 4 %}
             <a href="#" class="btn btn-primary btn-block float-right disabled">Seats Full</a>
             {% else %}
              <a href="{% url 'join' booking.id %}" class="btn btn-primary btn-block float-right">Join</a>
               {% endif %}

            <br><br>
            <a href="{% url 'leave' booking.id %}" class="btn btn-danger btn-block float-right" >Leave</a>
            <br><br>
            <a href="#" class="btn btn-warning btn-block float-right">Chat</a>
            <br><br>
            <a href="{% url 'booking_info' booking.id%}" class="btn btn-secondary btn-block float-right">Info</a>

        </div>

      </div>
    </div>
   </div>


   {%  endfor %}


{% endblock %}

src/bookings/templates/bookings/home.html
<!doctype html>
<html lang="en">

  <head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v4.0.1">
    <title>Cab Sharing</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/album/">

    <!-- Bootstrap core CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
<link href="{% static 'open-iconic/font/css/open-iconic-bootstrap.css' %}" rel="stylesheet"><link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css" rel="stylesheet">
    <!-- Favicons -->
<link rel="stylesheet" type="text/css" href="{% static 'cabsharing/style.css' %}">
<link rel="apple-touch-icon" href="/docs/4.5/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/4.5/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/4.5/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/4.5/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/4.5/assets/img/favicons/safari-pinned-tab.svg" color="#563d7c">
<link rel="icon" href="/docs/4.5/assets/img/favicons/favicon.ico">
<meta name="msapplication-config" content="/docs/4.5/assets/img/favicons/browserconfig.xml">
<meta name="theme-color" content="#563d7c">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }
      body{
        background-image: url('{% static 'homepage.png' %}');
        background-size: cover;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="album.css" rel="stylesheet">
  </head>
  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="/">CAB SHARING</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav ml-auto">
          {% if user.is_authenticated %}
          <a class="nav-item nav-link active" href="{% url 'user_profile' user.id %}"><i class="far fa-user-circle fa-lg"></i> {{user.username}}</a>
          <a class="nav-item nav-link active" href="{% url 'createbooking' %}">Create</a>
          <a class="nav-item nav-link active" href="{% url 'logout' %}">Logout</a>
          {% else %}
          <a class="nav-item nav-link active" href="{% url 'signup' %}">Sign Up</a>
          <a class="nav-item nav-link active" href="{% url 'signin' %}">Login</a>
          {% endif %}
         </div>
      </div>
    </nav>
</header>

{% if succ %}

<div class="alert alert-success" role="alert">
{{succ}}
</div>

{% endif %}

<div class = "container mt-5">
    <h1 class="display-2">Want to share a ride?</h1>
    <h5>Join a pool now.</h5>
    <br>
    <a href="{% url 'signup' %}" class="btn btn-outline-primary btn-large">Register now</a>
    <br><br>
    <a href="{% url 'bookings' %}" class="btn btn-outline-success btn-large">All Bookings</a>

</div>

<footer class="text-muted">
  <div class="container footer-container">
  </div>
</footer>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</html>

src/bookings/templates/bookings/index.html
{% extends 'base.html' %}
 {% load crispy_forms_tags %}
 {%load static%}
 {% load widget_tweaks %}
{% block content %}



{% if messages %}
{% for message in messages %}
<div class="alert alert-danger" role="alert">
{{message}}
</div>
{% endfor %}
{% endif %}

   <div class="row">
     <div class="col-md-2">
       <img src="{% static 'taxi.png' %}"  width="80" class="img-fluid">
     </div>
     <div class="col-md-10">
       <h1 class="display-4">All Bookings</h1>
     </div>

   </div>



<div class="row" style="margin-top:2rem">
  <div class="col-md-9 float-left">
    <button class="btn btn-outline-secondary btn-block text-left" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
       <i class="fas fa-filter"></i>  Filter
    </button>
  </div>
  <br><br><br>
  <div class="collapse" id="collapseExample">
    <form method="GET">
     <div class="well">
       <div class="row">
         <div class="form-group col-sm-4 col-md-3">
           {{ filter.form.destination.label_tag }}
           {% render_field filter.form.destination class="form-control" %}
         </div>
         <div class="form-group col-sm-4 col-md-3">
           {{ filter.form.pickup.label_tag }}
           {% render_field filter.form.pickup class="form-control" %}
         </div>
         <div class="form-group col-sm-4 col-md-3">
           {{ filter.form.date.label_tag }}
           {% render_field filter.form.date class="form-control" %}
         </div>
         <div class="form-group col-sm-4 col-md-3">
           {{ filter.form.time.label_tag }}
           {% render_field filter.form.time class="form-control" %}
         </div>
       </div>
       <div class="text-left">
         <button type="submit" class="btn btn-success">
           <span class="glyphicon glyphicon-search"></span> Search
         </button>
         <br>
       </div>
     </div>
   </form>
  </div>

</div>


{% for booking in filter.qs %}
 {% if booking.peopletogether == 4 %}
  <div class="card w-75 border-warning mt-4">
  <div class="card-body text-warning">
  {% else %}
  <div class="card w-75 border-success mt-4">
  <div class="card-body text-success">
    {% endif %}
    <div class="row">
      <div class="col-md-8">
       <div>
         <h3 class="card-title" style="display: inline">{{booking.pickup}} to {{booking.destination}}</h3>
          {%  for any in booking.members.all  %}
           {%  if any.user == request.user %}
              <img src="{% static 'confirm.png' %}" width = "35" class="img-fluid inline-block align-top">
            {%  endif %}
            {% endfor  %}
         </div>

        <h6>Time: {{booking.time}}</h6>
        <h6>Date: {{booking.date}}</h6>
        <h6>Members: {{booking.peopletogether}}</h6>
        <h6>Budget: {{booking.budget}}</h6>
        <h6>luggage: {{booking.luggage}}</h6>
        <h6>Created By: {{booking.user}}</h6>
      </div>
      <div class="col-md-4">


            {% if booking.peopletogether == 4 %}
             <a href="#" class="btn btn-primary btn-block float-right disabled">Seats Full</a>
             {% else %}
              <a href="{% url 'join' booking.id %}" class="btn btn-primary btn-block float-right">Join</a>
               {% endif %}

            <br><br>
            <a href="{% url 'leave' booking.id %}" class="btn btn-danger btn-block float-right" >Leave</a>
            <br><br>
            <a href= "{%url 'chat:room' booking.user %}" class="btn btn-warning btn-block float-right">Chat</a>
            <br><br>
            <a href="{% url 'booking_info' booking.id%}" class="btn btn-secondary btn-block float-right">Info</a>

        </div>

      </div>
    </div>
   </div>


   {%  endfor %}





{% endblock %}

src/bookings/templates/bookings/member_join.html
{% extends 'base.html' %}
  {% load static %}
{% block content %}

   <div class="container leave-container">
     <div class="row">
       <div class="col-md-4">
         <img src="{% static 'question-mark.png' %}" width = "300" class="img-fluid">
       </div>
       <div class="col-md-8">
         <form method="POST">
           {% csrf_token %}
           <h1>Are you sure you want to join this booking?</h1>
           <br><br>
           {{form}}
           <input type="submit" value="Join" class='btn btn-outline-secondary btn-lg'>
         </form>
       </div>
     </div>
    </div>

{% endblock %}

src/bookings/templates/bookings/member_leave.html
{% extends 'base.html' %}
 {%  load static %}
{% block content %}


   <div class="container leave-container">
     <div class="row">
       <div class="col-md-4">
         <img src="{% static 'question-mark.png' %}" width = "300" class="img-fluid">
       </div>
       <div class="col-md-8">
         <form method="POST">
           {% csrf_token %}
           <h1>Are you sure you want to leave this booking?</h1>
           <br><br>
           {{leaveform}}
           <input type="submit" value="Leave" class='btn btn-outline-danger btn-lg'>
         </form>
       </div>
     </div>
    </div>

{% endblock %}

src/bookings/templates/bookings/update.html
{% extends 'base.html' %}

{% block content %}
{% load crispy_forms_tags %}
{% load static %}

{% if messages %}
{% for message in messages %}
<div class="alert alert-danger" role="alert">
{{message}}
</div>
{% endfor %}
{% endif %}


   <div class = "container book-container">

     <div class="row">
       <div class="col-md-5">
         <img src="{% static 'feedback.png' %}" width = "280" class="img-fluid">
         <br><br><br>
         <h3>Update Booking</h3>
       </div>
       <div class="col-md-7">
         <form method="POST">
           {% csrf_token %}
           {{ booking_form|crispy }}
           <input type="submit" class="btn btn-outline-success" value="Submit">
         </form>
       </div>
     </div>
  </div>

{% endblock %}